### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by andreidev1** [sanvu88/lempmodules#1]
Hi . I saw you had this issue ( https://github.com/HansSchouten/Laravel-Pagebuilder/issues/41 ) . I am having the same issue you had . Could you please give me your discord/skype/whatsapp ID? so we can have a discuss about it please?
I've been trying for hours but I can not understand your solution that you found

**Comment by sanvu88** [comment]
yup, first you need to create the file **/config/pagebuilder.php** with the content here https://github.com/HansSchouten/Laravel-Pagebuilder/blob/master/config/pagebuilder.php

Then create **/themes/demo/blocks** directory. (You may need to create more folders if it says a missing directory)

Finally let's install the package

**Comment by Andreidavid918** [comment]
Hi thanks for the answer and answer . I really appreciate your time . I solved this problem and now is up and running .
I log in website manager without no issues but could you please tell me how can I add a theme? I've tried php artisan pagebuilder:create-theme/demo they work but I need to know how to add a website and start modifying things on it . Could you please help me with a source code of a demo and where could I add it ?

**Comment by Andreidavid918** [comment]
[https://imgur.com/a/OejHoC7](url)

I get only this and I cant even drag hello world to my empty page

**Comment by dartoran** [comment]
> yup, first you need to create the file **/config/pagebuilder.php** with the content here https://github.com/HansSchouten/Laravel-Pagebuilder/blob/master/config/pagebuilder.php
> 
> Then create **/themes/demo/blocks** directory. (You may need to create more folders if it says a missing directory)
> 
> Finally let's install the package

Can you guys post the solution?
